// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHBAVItfYkCtd7qAenUZKGB1MNqTAG76Q',
    appId: '1:648582297037:web:bf8b41aa1f01bf45a08084',
    messagingSenderId: '648582297037',
    projectId: 'tomorrowtwitter-91008',
    authDomain: 'tomorrowtwitter-91008.firebaseapp.com',
    storageBucket: 'tomorrowtwitter-91008.appspot.com',
    measurementId: 'G-JKVFXW5J3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE3EttB4YTaUA8iR4SE6ZQSxqH_O5Mzuk',
    appId: '1:648582297037:android:1a391da5ffbd3eeba08084',
    messagingSenderId: '648582297037',
    projectId: 'tomorrowtwitter-91008',
    storageBucket: 'tomorrowtwitter-91008.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRaiP0bPugdTHoBkGbOKYWo8EFg-VKTKw',
    appId: '1:648582297037:ios:3315db17187f7018a08084',
    messagingSenderId: '648582297037',
    projectId: 'tomorrowtwitter-91008',
    storageBucket: 'tomorrowtwitter-91008.appspot.com',
    iosBundleId: 'com.example.twitterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRaiP0bPugdTHoBkGbOKYWo8EFg-VKTKw',
    appId: '1:648582297037:ios:d83e4923de6aab95a08084',
    messagingSenderId: '648582297037',
    projectId: 'tomorrowtwitter-91008',
    storageBucket: 'tomorrowtwitter-91008.appspot.com',
    iosBundleId: 'com.example.twitterApp.RunnerTests',
  );
}
